name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

  fluttertoast: ^8.2.12
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  shared_preferences: ^2.5.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.18.4
  webview_flutter_platform_interface: ^2.10.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.5
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  flutter_contacts: ^1.1.6
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  latlong2: ^0.9.0
  flutter_map: ^8.1.1
  flutter_rating_bar: ^4.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
 
  assets:
    - assets/
    - assets/animations/
    - assets/logo.png
    - assets/login_page_background (2).jpg
    - assets/animations/location.json
    - assets/animations/oportunity.json
  
fonts:
    - family: Poppins
      fonts:
        - asset: ./fonts/Poppins/Poppins-Black.ttf
          weight: 500
        - asset: ./fonts/Poppins/Poppins-Bold.ttf
          weight: 600
        - asset: ./fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 700
        - asset: ./fonts/Poppins/Poppins-Italic.ttf
          weight: 400