// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHMbEb6Kvj2eAjsqQDjkGcR8xCq3YVEg',
    appId: '1:1062374052181:web:7cc7bc99ad5b6eec8c1fdc',
    messagingSenderId: '1062374052181',
    projectId: 'women-safety-app-680e9',
    authDomain: 'women-safety-app-680e9.firebaseapp.com',
    storageBucket: 'women-safety-app-680e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl8HUVEiZC4r_aet9vyyQFJYX-jfbkZBA',
    appId: '1:1062374052181:android:5ab0ceb9fd68cf5a8c1fdc',
    messagingSenderId: '1062374052181',
    projectId: 'women-safety-app-680e9',
    storageBucket: 'women-safety-app-680e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5sWxR0BueJCCCCMtL8LrAjSWQsZuIgw',
    appId: '1:1062374052181:ios:3965ace7c5a1a3558c1fdc',
    messagingSenderId: '1062374052181',
    projectId: 'women-safety-app-680e9',
    storageBucket: 'women-safety-app-680e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5sWxR0BueJCCCCMtL8LrAjSWQsZuIgw',
    appId: '1:1062374052181:ios:3965ace7c5a1a3558c1fdc',
    messagingSenderId: '1062374052181',
    projectId: 'women-safety-app-680e9',
    storageBucket: 'women-safety-app-680e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnHMbEb6Kvj2eAjsqQDjkGcR8xCq3YVEg',
    appId: '1:1062374052181:web:159c526c65d8f8a08c1fdc',
    messagingSenderId: '1062374052181',
    projectId: 'women-safety-app-680e9',
    authDomain: 'women-safety-app-680e9.firebaseapp.com',
    storageBucket: 'women-safety-app-680e9.firebasestorage.app',
  );
}
